query getGameListByName {
  getGameList(sort: "name", first: 50) {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
          collection {
            slug
          }
        }
        data {
          ...GameParts
        }
      }
    }
  }
}

query getBacklogGameListByName {
  getGameList(
    sort: "name"
    filter: { status: { in: ["Playing", "Backlog"] } }
    first: 50
  ) {
    totalCount
    edges {
      node {
        id
        sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
          collection {
            slug
          }
        }
        data {
          ...GameParts
        }
      }
    }
  }
}
