query gamesByName {
  gameConnection(sort: "name", first: 50) {
    ...ListParts
  }
}

query backlogGamesByName {
  gameConnection(
    sort: "name"
    filter: { status: { in: ["Playing", "Backlog"] } }
    first: 50
  ) {
    ...ListParts
  }
}

query finishedGamesByName {
  gameConnection(
    sort: "name"
    filter: { status: { eq: "Finished" } }
    first: 50
  ) {
    ...ListParts
  }
}
